### ISSUE TITLE
Using tt_content.stdWrap.innerWrap

### ISSUE THREAD

**Issue by s-leger** [typo3-themes/themes_gridelements#22] opened 2015-04-30 10:40 UTC
Hi,
Using a copy of tt_content.stdWrap for gridelements break default grid settings for custom grids, as we need to make config in two places (in tt_content for all but default content_frame and in gridelements.default) . 

Why not simply use base tt_content.stdWrap.innerWrap for all contents, not breaking things at all ?

I mean : tt_content.stdWrap.innerWrap..10.cObject and 30.cObject are both cType case, making it possible to write a clean sub case for gridelements_pi1 based on backend_layout ?

**Comment by Bunnyfield** [comment] 2015-04-30 11:54
Could you please specify, what exactly is really broken?

If you modify the default "content_frame" settings, this should be copied together with the rest of the innerWrap settings, so I don't see any problems with that.

Using the copy gives us the option to deal differently with each gridelement layout without touching the original innerWrap at all. We don't need just additional stuff but sometimes we have to remove settings as well, so handling that with CASE or "if" IMHO would result in a complete mess within the original innerWrap.

Having a reference here would not help either, since sometimes we have to deactivate stuff, which can not be done with references at all.

To make sure nothing gets doubled there is a small part in the default setup of themes_gridelements which is inserted after copying the original setup.

if {
  value = gridelements_pi1
  equals.field = CType
  negate = 1
}

So from my point of view nothing should be broken there.

**Comment by s-leger** [comment] 2015-04-30 12:24
It's a matter of when things get done.

If i modify default content frame after theme_gridelements, all but the default work. Reference magick.
For the default to work, i have to set up also in gridelements.innerWrap.

It's ok only if i do modifications before gridelements include.

simply replace
if {
value = gridelements_pi1
equals.field = CType
negate = 1
}
by something like
if{
value =
isInList.field = backend_layout 
}

and then use value := addtoList(myLayout)
when needed would have do the trick as well

Others than classes (10.cObject and 30.cObject) are allready a cType case, so no risk to mess up here.

**Comment by Bunnyfield** [comment] 2015-04-30 12:56
First of all, you already named it: It's a matter of when tings get done, so nothing is broken as long as you make sure that the steps are taken in the correct order.

Second the isInList stuff would not change anything, since it would still be a matter of when things get done at least for the elements in the list.

The solutions is relatively easy: Just make sure things are happening in the right order.

In theme_bootstrap setup.txt you will find the following line:
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:themes_gridelements/Configuration/TypoScript/setup.txt">

Now in theme_bootstrap_highland you will find this one:
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:theme_bootstrap/Configuration/TypoScript/setup.txt">

Since theme_bootstrap_highland is just one theme based on theme_bootstrap I guess this comes close to your current scenario. Now you justhave to make sure, your changes to tt_content.stdWrap.innerWrap will be included before the line including stuff from theme_bootstrap.

I did not test it yet, but the expected behaviour should be that tt_content.stdWrap.innerWrap gets modified before it will be copied to the gridelements setups.

**Comment by s-leger** [comment] 2015-04-30 13:56
You're right.
On the other hand, IsInList stuff would make any other gridelement work as it, and prevent inclusion order dependencies.

**Comment by Bunnyfield** [comment] 2015-04-30 14:10
Yes and no - since people might like to get your changes for the default grid elements as well - so currently the order of <INCLUDE blah/> parts is the only way to be on the safe side for everybody. Afterwards you can easily remove superfluous stuff and of course you can include as many conditions in your theme setup as you like.

**Closed by Bunnyfield** 2015-04-30 14:10 UTC
